// API Configuration
export const apiConfig = {
  contactEndpoint: process.env.NEXT_PUBLIC_CONTACT_API_URL || 'https://6u0pto5yr2.execute-api.eu-west-2.amazonaws.com/contact',
}

export const siteConfig = {
  name: 'Bates Groundworks',
  tagline: 'Landscaping & Construction',
  description: 'Professional landscape gardening, garden maintenance, and general building services. Small jobs, Big jobs!',
  contact: {
    name: 'Robbie',
    phone: '07773 552028',
    email: 'b8ssolutions@gmail.com',
  },
  cta: 'Get in touch for a free quote',
  services: [
    {
      title: 'Landscape Gardening',
      slug: 'landscape-gardening',
      description: 'Transform your outdoor space with professional garden design, planting, and hardscaping.',
      longDescription: 'Whether you want a complete garden transformation or just need help with specific areas, we bring your vision to life. From initial design concepts through to final planting, we handle every aspect of your landscaping project.',
      features: [
        'Garden design and planning',
        'Planting schemes',
        'Lawn installation (turf/seed)',
        'Hedging and screening',
        'Water features',
        'Garden lighting',
      ],
    },
    {
      title: 'Garden Maintenance',
      slug: 'garden-maintenance',
      description: 'Keep your garden looking its best with regular maintenance and seasonal care.',
      longDescription: 'A beautiful garden needs regular care. We offer flexible maintenance packages to keep your outdoor space looking pristine all year round, from weekly visits to seasonal one-off tidy-ups.',
      features: [
        'Regular maintenance contracts',
        'One-off garden tidy-ups',
        'Hedge trimming',
        'Lawn care (mowing, feeding, aeration)',
        'Seasonal planting',
        'Weed control',
      ],
    },
    {
      title: 'General Building',
      slug: 'general-building',
      description: 'Quality building work from extensions to repairs. No job too small.',
      longDescription: 'From patios and driveways to fencing and retaining walls, we deliver quality construction work that stands the test of time. Every project is completed to the highest standards with attention to detail.',
      features: [
        'Patios and paving',
        'Decking',
        'Fencing and gates',
        'Retaining walls',
        'Drainage solutions',
        'Driveways',
      ],
    },
  ],
  process: [
    {
      step: 1,
      title: 'Free Consultation',
      description: 'We visit your property to discuss your requirements and provide expert advice.',
    },
    {
      step: 2,
      title: 'Quote & Design',
      description: 'You receive a detailed quote with clear pricing. For larger projects, we provide design plans.',
    },
    {
      step: 3,
      title: 'Project Execution',
      description: 'Our skilled team completes the work efficiently, keeping you informed throughout.',
    },
    {
      step: 4,
      title: 'Final Walkthrough',
      description: 'We walk through the completed work together to ensure your complete satisfaction.',
    },
  ],
  navigation: [
    { label: 'Home', href: '/' },
    { label: 'Services', href: '/services' },
    { label: 'Projects', href: '/projects' },
    { label: 'About', href: '/about' },
    { label: 'Contact', href: '/contact' },
  ],
  about: {
    story: {
      title: 'Our Story',
      paragraphs: [
        'Bates Groundworks was founded with a simple mission: to deliver quality landscaping and building work that stands the test of time. What started as a one-man operation has grown into a trusted local business serving Herefordshire, Worcestershire, and Gloucestershire.',
        'With years of hands-on experience in the trade, we understand that every outdoor space is unique. Whether it\'s a small garden tidy-up or a complete property transformation, we bring the same level of care, attention to detail, and professional craftsmanship to every project.',
        'We believe in honest pricing, clear communication, and doing the job right first time. That\'s why so much of our work comes from recommendations and returning customers.',
      ],
    },
    values: [
      {
        title: 'Quality Workmanship',
        description: 'Every project is completed to the highest standards using quality materials and proven techniques.',
        icon: 'quality',
      },
      {
        title: 'Reliability',
        description: 'We turn up when we say we will, keep you informed, and deliver on our promises.',
        icon: 'reliability',
      },
      {
        title: 'Clear Communication',
        description: 'No jargon, no hidden costs. We explain everything clearly and keep you updated throughout.',
        icon: 'communication',
      },
      {
        title: 'Customer Focus',
        description: 'Your satisfaction is our priority. We work with you to bring your vision to life.',
        icon: 'customer',
      },
    ],
    serviceAreas: [
      'Herefordshire',
      'Worcestershire',
      'Gloucestershire',
      'Powys',
      'Monmouthshire',
    ],
    credentials: [
      'Fully insured',
      'Public liability coverage',
      'Waste carrier licence',
      'Free quotes and consultations',
    ],
  },
  contactPage: {
    hero: {
      title: 'Get In Touch',
      subtitle: 'Ready to transform your outdoor space? Contact us for a free, no-obligation quote.',
    },
    form: {
      services: [
        'Landscape Gardening',
        'Garden Maintenance',
        'General Building',
        'Patios & Paving',
        'Fencing & Gates',
        'Other',
      ],
    },
    info: {
      hours: 'Monday - Friday: 8am - 6pm\nSaturday: 9am - 4pm\nSunday: Closed',
      response: 'We aim to respond to all enquiries within 24 hours.',
    },
  },
  projects: [
    {
      id: '1',
      slug: 'garden-transformation-surrey',
      title: 'Complete Garden Transformation',
      description: 'A full garden redesign including new patio, lawn, and planting beds.',
      category: 'landscaping' as const,
      location: 'Herefordshire',
      completedDate: '2024-10',
      featured: true,
      services: ['Garden design and planning', 'Patio installation', 'Lawn installation', 'Planting'],
    },
    {
      id: '2',
      slug: 'patio-decking-project',
      title: 'Patio & Decking Installation',
      description: 'Modern patio with composite decking and outdoor lighting.',
      category: 'building' as const,
      location: 'Worcestershire',
      completedDate: '2024-09',
      featured: true,
      services: ['Patios and paving', 'Decking', 'Garden lighting'],
    },
    {
      id: '3',
      slug: 'hedge-trimming-maintenance',
      title: 'Regular Garden Maintenance',
      description: 'Ongoing maintenance contract for a large residential property.',
      category: 'maintenance' as const,
      location: 'Gloucestershire',
      completedDate: '2024-08',
      featured: false,
      services: ['Hedge trimming', 'Lawn care', 'Seasonal planting'],
    },
    {
      id: '4',
      slug: 'driveway-installation',
      title: 'Block Paving Driveway',
      description: 'New block paved driveway with drainage solutions.',
      category: 'building' as const,
      location: 'Herefordshire',
      completedDate: '2024-07',
      featured: true,
      services: ['Driveways', 'Drainage solutions'],
    },
    {
      id: '5',
      slug: 'fencing-gates-project',
      title: 'Fencing & Gate Installation',
      description: 'New close board fencing with bespoke wooden gate.',
      category: 'building' as const,
      location: 'Worcestershire',
      completedDate: '2024-06',
      featured: false,
      services: ['Fencing and gates'],
    },
    {
      id: '6',
      slug: 'lawn-renovation',
      title: 'Lawn Renovation Project',
      description: 'Complete lawn renovation including levelling, seeding, and initial care.',
      category: 'landscaping' as const,
      location: 'Gloucestershire',
      completedDate: '2024-05',
      featured: false,
      services: ['Lawn installation', 'Garden maintenance'],
    },
  ],
}
